### ISSUE TITLE
Html file?

### ISSUE THREAD

**Issue by ratnanil** [SilviaJuen/cma-week2#1]
I see there is no 'html' file in your repo. In case you are working with Rmarkdown, creating an html file is very simple. Simpliy 'render' the document using the 'Render' Button or the keyboard shortcut <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>K</kbd>\n\n PS: This issue was generated automatically.

**Comment by SilviaJuen** [comment]
I am sorry, but there is a html file in the folder. If you would like to see an pdf or something else, I can upload it of course. But with my Knowledge at the moment, I do not understand what you mean, sorry.

Silvia Juen

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows

Von: ***@***.***>
Gesendet: Mittwoch, 11. Mai 2022 10:35
An: ***@***.***>
Cc: ***@***.***>
Betreff: [SilviaJuen/cma-week2] Html file? (Issue #1)


I see there is no 'html' file in your repo. In case you are working with Rmarkdown, creating an html file is very simple. Simpliy 'render' the document using the 'Render' Button or the keyboard shortcut Ctrl+Shift+K\n\n PS: This issue was generated automatically.

**Comment by ratnanil** [comment]
It was my mistake, I hadn't pulled your latest changes! Sorry for that :-)
